# coding: utf-8

"""
    Monitoring Hub API

    API to access data from the monitoring hub. <br>Each monitoring element available is described by the path *source/partition/task/entity*. <br> - **source**: DIM, savesets, WinCC, prometheus, simulation, ... - **partition**: LHCb, TDET, VELO, requestID, ... - **task**: the name of the task publishing the data, for simulation event type number - **entity**: the item to monitoring, such as histogram, trend, ... 

    The version of the OpenAPI document: 1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from MonitoringHub.models.root import ROOT
from MonitoringHub.models.trend_inner_inner import TrendInnerInner
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

APIHUBGETDATA200RESPONSE_ONE_OF_SCHEMAS = ["List[List[TrendInnerInner]]", "ROOT"]

class ApiHubGetData200Response(BaseModel):
    """
    ApiHubGetData200Response
    """
    # data type: ROOT
    oneof_schema_1_validator: Optional[ROOT] = None
    # data type: List[List[TrendInnerInner]]
    oneof_schema_2_validator: Optional[List[List[TrendInnerInner]]] = None
    actual_instance: Optional[Union[List[List[TrendInnerInner]], ROOT]] = None
    one_of_schemas: Set[str] = { "List[List[TrendInnerInner]]", "ROOT" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ApiHubGetData200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: ROOT
        if not isinstance(v, ROOT):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ROOT`")
        else:
            match += 1
        # validate data type: List[List[TrendInnerInner]]
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ApiHubGetData200Response with oneOf schemas: List[List[TrendInnerInner]], ROOT. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ApiHubGetData200Response with oneOf schemas: List[List[TrendInnerInner]], ROOT. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ROOT
        try:
            instance.actual_instance = ROOT.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into List[List[TrendInnerInner]]
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ApiHubGetData200Response with oneOf schemas: List[List[TrendInnerInner]], ROOT. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ApiHubGetData200Response with oneOf schemas: List[List[TrendInnerInner]], ROOT. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], List[List[TrendInnerInner]], ROOT]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


